In [1]:
import torch
import os
import csv
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda, Compose
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd
import numpy as np
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical

In [2]:

train_data = pd.read_csv("iris.csv")

print(train_data)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

            species  
0    

In [3]:
X = train_data.iloc[:,0:3].values
print(X)

[[5.1 3.5 1.4]
 [4.9 3.  1.4]
 [4.7 3.2 1.3]
 [4.6 3.1 1.5]
 [5.  3.6 1.4]
 [5.4 3.9 1.7]
 [4.6 3.4 1.4]
 [5.  3.4 1.5]
 [4.4 2.9 1.4]
 [4.9 3.1 1.5]
 [5.4 3.7 1.5]
 [4.8 3.4 1.6]
 [4.8 3.  1.4]
 [4.3 3.  1.1]
 [5.8 4.  1.2]
 [5.7 4.4 1.5]
 [5.4 3.9 1.3]
 [5.1 3.5 1.4]
 [5.7 3.8 1.7]
 [5.1 3.8 1.5]
 [5.4 3.4 1.7]
 [5.1 3.7 1.5]
 [4.6 3.6 1. ]
 [5.1 3.3 1.7]
 [4.8 3.4 1.9]
 [5.  3.  1.6]
 [5.  3.4 1.6]
 [5.2 3.5 1.5]
 [5.2 3.4 1.4]
 [4.7 3.2 1.6]
 [4.8 3.1 1.6]
 [5.4 3.4 1.5]
 [5.2 4.1 1.5]
 [5.5 4.2 1.4]
 [4.9 3.1 1.5]
 [5.  3.2 1.2]
 [5.5 3.5 1.3]
 [4.9 3.1 1.5]
 [4.4 3.  1.3]
 [5.1 3.4 1.5]
 [5.  3.5 1.3]
 [4.5 2.3 1.3]
 [4.4 3.2 1.3]
 [5.  3.5 1.6]
 [5.1 3.8 1.9]
 [4.8 3.  1.4]
 [5.1 3.8 1.6]
 [4.6 3.2 1.4]
 [5.3 3.7 1.5]
 [5.  3.3 1.4]
 [7.  3.2 4.7]
 [6.4 3.2 4.5]
 [6.9 3.1 4.9]
 [5.5 2.3 4. ]
 [6.5 2.8 4.6]
 [5.7 2.8 4.5]
 [6.3 3.3 4.7]
 [4.9 2.4 3.3]
 [6.6 2.9 4.6]
 [5.2 2.7 3.9]
 [5.  2.  3.5]
 [5.9 3.  4.2]
 [6.  2.2 4. ]
 [6.1 2.9 4.7]
 [5.6 2.9 3.6]
 [6.7 3.1 4.4]
 [5.6 3.  

In [4]:
y = train_data.iloc[:,4].values
print(y[0:4])

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [5]:
print(X.shape) #4 kolumny danych do nauki
print(y.shape) #wyniki 

(150, 3)
(150,)


In [6]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)
print(y1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [7]:
Y = pd.get_dummies(y1).values
print(Y[0:5])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)



In [9]:
print(X_train[0:5])

[[6.4 3.1 5.5]
 [5.4 3.  4.5]
 [5.2 3.5 1.5]
 [6.1 3.  4.9]
 [6.4 2.8 5.6]]


In [10]:
print(y_train[0:5])

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]]


In [11]:
print(X_test[0:5])

[[5.8 2.8 5.1]
 [6.  2.2 4. ]
 [5.5 4.2 1.4]
 [7.3 2.9 6.3]
 [5.  3.4 1.5]]


In [12]:
print(y_test[0:5])

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]]


In [13]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3)
  ])
model

In [14]:
model.compile(optimizer='RMSprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [15]:
model.fit(X_train, y_train, batch_size=50, epochs=100)

Epoch 1/100
3/3 [==============================] - 1s 2ms/step - loss: 9.1336 - accuracy: 0.3917
Epoch 2/100
3/3 [==============================] - 0s 1ms/step - loss: 9.1336 - accuracy: 0.3917
Epoch 3/100
3/3 [==============================] - 0s 2ms/step - loss: 9.1336 - accuracy: 0.3917
Epoch 4/100
3/3 [==============================] - 0s 2ms/step - loss: 9.1336 - accuracy: 0.3917
Epoch 5/100
3/3 [==============================] - 0s 2ms/step - loss: 9.1336 - accuracy: 0.3917
Epoch 6/100
3/3 [==============================] - 0s 1ms/step - loss: 9.1336 - accuracy: 0.3917
Epoch 7/100
3/3 [==============================] - 0s 2ms/step - loss: 9.1336 - accuracy: 0.3917
Epoch 8/100
3/3 [==============================] - 0s 1ms/step - loss: 9.1336 - accuracy: 0.3917
Epoch 9/100
3/3 [==============================] - 0s 2ms/step - loss: 9.1336 - accuracy: 0.3917
Epoch 10/100
3/3 [==============================] - 0s 1ms/step - loss: 9.1336 - accuracy: 0.3917
Epoch 11/100
3/3 [===========

3/3 [==============================] - 0s 2ms/step - loss: 9.1336 - accuracy: 0.3917
Epoch 85/100
3/3 [==============================] - 0s 2ms/step - loss: 9.1336 - accuracy: 0.3917
Epoch 86/100
3/3 [==============================] - 0s 2ms/step - loss: 9.1336 - accuracy: 0.3917
Epoch 87/100
3/3 [==============================] - 0s 2ms/step - loss: 9.1336 - accuracy: 0.3917
Epoch 88/100
3/3 [==============================] - 0s 3ms/step - loss: 9.1336 - accuracy: 0.3917
Epoch 89/100
3/3 [==============================] - 0s 1ms/step - loss: 9.1336 - accuracy: 0.3917
Epoch 90/100
3/3 [==============================] - 0s 3ms/step - loss: 9.1336 - accuracy: 0.3917
Epoch 91/100
3/3 [==============================] - 0s 999us/step - loss: 9.1336 - accuracy: 0.3917
Epoch 92/100
3/3 [==============================] - 0s 3ms/step - loss: 9.1336 - accuracy: 0.3917
Epoch 93/100
3/3 [==============================] - 0s 1ms/step - loss: 9.1336 - accuracy: 0.3917
Epoch 94/100
3/3 [=============

In [16]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 6.984508037567139
Test accuracy: 0.5666666626930237


In [22]:
y_pred = model.predict(X_test)


In [18]:
model.history

In [19]:
actual = np.argmax(y_test,axis=1)
predicted = np.argmax(y_pred,axis=1)
print(f"Actual   : {actual}")
print(f"Predicted: {predicted}")

Actual   : [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
Predicted: [1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1]
