In [1]:
#######################################################
#BM.
#
#             Ekstrakcjach cech z *png -> Hsv
#             Srednia                H,S,V
#             Dominanta              H,S,V
#             Odchylenie standardowe H,S,V
#             Wariacja               H,S,V
#             ID Pacjenta
#             KLasa:                 n-brak raka
#                                    y-rak
#
#      Metodyka:
#             Użycie zbioru testowego 25% z bib. sklearn
#             "Naive Bayes",
#             "Neural Network 8,8,8",
#             "Neural Network 1n",
#             "Nearest Neighbors 3n",
#             "Nearest Neighbors 5n",
#             "Decision Tree",
#             "Random Forest",
#             "Neural Network default",
#             "AdaBoost"
#
#
#########################################################

In [2]:
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [3]:
df = pd.read_csv("D:/hsv_all.csv", header='infer')
df = df[["srH","srS","srV","dH","dS","dV","odH","odS","odV","wH","wS","wV","id","class"]]
column_names = ['srH','srS','srV','dH','dS','dV','odH','odS','odV','wH','wS','wV','id','class']

In [4]:
#Podział
z = df.drop("class",axis=1)
X = z.drop("id", axis=1)
y = df['class']

df['class'].value_counts()

n    198738
y     78786
Name: class, dtype: int64

In [5]:
df

srH       srS       srV        dH        dS        dV       odH  \
0       0.812857  0.097987  0.909216  0.833333  0.004098  0.956863  0.229346   
1       0.896696  0.280624  0.803631  0.916667  0.274882  0.835294  0.038154   
2       0.895134  0.241859  0.823581  0.888889  0.240385  0.819608  0.047173   
3       0.901549  0.299680  0.800160  0.916667  0.333333  0.823529  0.022068   
4       0.752751  0.075313  0.894240  0.833333  0.004115  0.952941  0.250369   
...          ...       ...       ...       ...       ...       ...       ...   
277519  0.865517  0.347641  0.682951  0.833333  0.020661  0.949020  0.118120   
277520  0.842576  0.365019  0.593864  0.833333  0.500000  0.592157  0.046193   
277521  0.831393  0.394650  0.546113  0.833333  0.500000  0.545098  0.035610   
277522  0.863905  0.372944  0.623272  0.833333  0.500000  0.662745  0.035065   
277523  0.841669  0.350723  0.609832  0.833333  0.500000  0.572549  0.073717   

             odS       odV        wH        wS        wV    id class  
0       0.076772  0.041590  0.052599  0.005894  0.001730  9077     n  
1       0.073372  0.072833  0.001456  0.005383  0.005305  9077     n  
2       0.066294  0.036424  0.002225  0.004395  0.001327  9077     n  
3       0.060969  0.049578  0.000487  0.003717  0.002458  9077     n  
4       0.103110  0.092301  0.062685  0.010632  0.008519  9077     n  
...          ...       ...       ...       ...       ...   ...   ...  
277519  0.174198  0.148556  0.013952  0.030345  0.022069  8863     y  
277520  0.115236  0.101251  0.002134  0.013279  0.010252  8863     y  
277521  0.094836  0.083799  0.001268  0.008994  0.007022  8863     y  
277522  0.094383  0.087594  0.001230  0.008908  0.007673  8863     y  
277523  0.142105  0.128203  0.005434  0.020194  0.016436  8863     y  

[277524 rows x 14 columns]

In [6]:
df = df.drop('id', axis=1)


In [7]:
df

srH       srS       srV        dH        dS        dV       odH  \
0       0.812857  0.097987  0.909216  0.833333  0.004098  0.956863  0.229346   
1       0.896696  0.280624  0.803631  0.916667  0.274882  0.835294  0.038154   
2       0.895134  0.241859  0.823581  0.888889  0.240385  0.819608  0.047173   
3       0.901549  0.299680  0.800160  0.916667  0.333333  0.823529  0.022068   
4       0.752751  0.075313  0.894240  0.833333  0.004115  0.952941  0.250369   
...          ...       ...       ...       ...       ...       ...       ...   
277519  0.865517  0.347641  0.682951  0.833333  0.020661  0.949020  0.118120   
277520  0.842576  0.365019  0.593864  0.833333  0.500000  0.592157  0.046193   
277521  0.831393  0.394650  0.546113  0.833333  0.500000  0.545098  0.035610   
277522  0.863905  0.372944  0.623272  0.833333  0.500000  0.662745  0.035065   
277523  0.841669  0.350723  0.609832  0.833333  0.500000  0.572549  0.073717   

             odS       odV        wH        wS        wV class  
0       0.076772  0.041590  0.052599  0.005894  0.001730     n  
1       0.073372  0.072833  0.001456  0.005383  0.005305     n  
2       0.066294  0.036424  0.002225  0.004395  0.001327     n  
3       0.060969  0.049578  0.000487  0.003717  0.002458     n  
4       0.103110  0.092301  0.062685  0.010632  0.008519     n  
...          ...       ...       ...       ...       ...   ...  
277519  0.174198  0.148556  0.013952  0.030345  0.022069     y  
277520  0.115236  0.101251  0.002134  0.013279  0.010252     y  
277521  0.094836  0.083799  0.001268  0.008994  0.007022     y  
277522  0.094383  0.087594  0.001230  0.008908  0.007673     y  
277523  0.142105  0.128203  0.005434  0.020194  0.016436     y  

[277524 rows x 13 columns]

In [8]:
target_column = ['class'] 
predictors = list(set(list(df.columns))-set(target_column))
df[predictors] = df[predictors]/df[predictors].max()
df.describe().transpose()

count      mean       std       min       25%       50%       75%  max
srH  277524.0  0.845475  0.120105  0.055965  0.824095  0.875857  0.915541  1.0
srS  277524.0  0.253032  0.114593  0.005304  0.159377  0.256171  0.337536  1.0
srV  277524.0  0.839956  0.096873  0.012452  0.781995  0.870737  0.916391  1.0
dH   277524.0  0.733396  0.337290  0.000000  0.839744  0.839744  0.923718  1.0
dS   277524.0  0.180336  0.188981  0.000000  0.012397  0.030303  0.333333  1.0
dV   277524.0  0.871877  0.104217  0.011765  0.839216  0.905882  0.949020  1.0
odH  277524.0  0.291823  0.229888  0.003602  0.088779  0.221857  0.466723  1.0
odS  277524.0  0.278702  0.107964  0.005221  0.200577  0.266224  0.344563  1.0
odV  277524.0  0.203863  0.092849  0.002837  0.137714  0.197207  0.255761  1.0
wH   277524.0  0.138009  0.180072  0.000013  0.007882  0.049221  0.217830  1.0
wS   277524.0  0.089331  0.069859  0.000027  0.040231  0.070875  0.118723  1.0
wV   277524.0  0.050181  0.048538  0.000008  0.018965  0.038891  0.065414  1.0

In [9]:
predictors

['dV', 'wS', 'odV', 'wV', 'wH', 'srV', 'odH', 'srH', 'srS', 'dS', 'dH', 'odS']

In [10]:
target_column

['class']

In [11]:
X = df[predictors].values
y = np.ravel(df[target_column].values)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=40)
print(X_train.shape); print(X_test.shape)

(208143, 12)
(69381, 12)


In [12]:
y

array(['n', 'n', 'n', ..., 'y', 'y', 'y'], dtype=object)

In [13]:
X

array([[0.95686275, 0.03386729, 0.09757241, ..., 0.00409836, 0.83974359,
        0.18403066],
       [0.83529412, 0.03093376, 0.17087048, ..., 0.27488152, 0.92371795,
        0.17587997],
       [0.81960784, 0.02525311, 0.08545342, ..., 0.24038462, 0.8957265 ,
        0.15891228],
       ...,
       [0.54509804, 0.05167963, 0.19659745, ..., 0.5       , 0.83974359,
        0.22733155],
       [0.6627451 , 0.05118616, 0.20549917, ..., 0.5       , 0.83974359,
        0.22624358],
       [0.57254902, 0.11603472, 0.30077035, ..., 0.5       , 0.83974359,
        0.34063869]])

In [14]:
################################
# Kilka klasyfikatorów
################################

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [16]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_moons, make_circles, make_classification
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

classifiers = [
    GaussianNB(),
    MLPClassifier(hidden_layer_sizes=(10), activation='relu', solver='adam', max_iter=500),
    KNeighborsClassifier(2),
    KNeighborsClassifier(5),
    DecisionTreeClassifier(criterion = 'entropy', random_state = 0),
    RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1),
    MLPClassifier(alpha=1, max_iter=1000),
    AdaBoostClassifier()
]

names = [
    "Naive Bayes",
    "Neural Network 10n",
    "Nearest Neighbors 2n",
    "Nearest Neighbors 5n",
    "Decision Tree",
    "Random Forest",
    "Neural Network default",
    "AdaBoost"
]


In [17]:
for i in range(0,len(classifiers)):
    print("klasyfikator : ", names[i])
    
   
    classifier = classifiers[i]
    classifier.fit(X_train, Y_train)
    Y_pred = classifier.predict(X_test)
    
    cm = confusion_matrix(Y_test, Y_pred)
    print("Macierz pomyłek: \n", cm)
   
    matrix = classification_report(Y_test,Y_pred)
    print('Classification report : \n',matrix)
    
    print("----------------------------------------------------------------")
    

klasyfikator :  Naive Bayes
Macierz pomyłek: 
 [[34201 15496]
 [ 3683 16001]]
Classification report : 
               precision    recall  f1-score   support

           n       0.90      0.69      0.78     49697
           y       0.51      0.81      0.63     19684

    accuracy                           0.72     69381
   macro avg       0.71      0.75      0.70     69381
weighted avg       0.79      0.72      0.74     69381

----------------------------------------------------------------
klasyfikator :  Neural Network 10n
Macierz pomyłek: 
 [[45592  4105]
 [ 6153 13531]]
Classification report : 
               precision    recall  f1-score   support

           n       0.88      0.92      0.90     49697
           y       0.77      0.69      0.73     19684

    accuracy                           0.85     69381
   macro avg       0.82      0.80      0.81     69381
weighted avg       0.85      0.85      0.85     69381

----------------------------------------------------------------
k

In [18]:
print("end")

end
